### ISSUE TITLE
negative pages

### ISSUE THREAD

**Issue by jensopetersen** [wolfgangmm/ShakespeareDemo#27]
For each page displayed, two $lowerBound and two $upperBound are generated. The values for the first five pages are as follows.

1
$lowerBound): 1
$upperBound): 4
$lowerBound): 1
$upperBound): 8

2
$lowerBound): 1
$upperBound): 4
$lowerBound): 1
$upperBound): 8

3
$lowerBound): 2
$upperBound): 5
$lowerBound): 1
$upperBound): 8

4
$lowerBound): 3
$upperBound): 6
$lowerBound): 1
$upperBound): 8

5
$lowerBound): 4
$upperBound): 7
$lowerBound): -2
$upperBound): 8

On the fifth page, a negative $lowerBound is displayed.

**Comment by wolfgangmm** [comment]
Hopefully fixed now.
